// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAua1SaD1Yi1As1tpGYfVgxOS6aOhwT8N0',
    appId: '1:776638379002:web:7cdd9c9153462a0643ea43',
    messagingSenderId: '776638379002',
    projectId: 'esumbong-1fd58',
    authDomain: 'esumbong-1fd58.firebaseapp.com',
    storageBucket: 'esumbong-1fd58.firebasestorage.app',
    measurementId: 'G-KGDE8EJFVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkEYRuvWv8h0YUbYw7pp-qh_fhz5e_t8I',
    appId: '1:776638379002:android:be5dd13fd102d4bb43ea43',
    messagingSenderId: '776638379002',
    projectId: 'esumbong-1fd58',
    storageBucket: 'esumbong-1fd58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15oW11eQIxZnIRP1m1ME0qhIxfrCgPpY',
    appId: '1:776638379002:ios:2cfc1fb88ddd439143ea43',
    messagingSenderId: '776638379002',
    projectId: 'esumbong-1fd58',
    storageBucket: 'esumbong-1fd58.firebasestorage.app',
    iosBundleId: 'com.example.esumbong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA15oW11eQIxZnIRP1m1ME0qhIxfrCgPpY',
    appId: '1:776638379002:ios:2cfc1fb88ddd439143ea43',
    messagingSenderId: '776638379002',
    projectId: 'esumbong-1fd58',
    storageBucket: 'esumbong-1fd58.firebasestorage.app',
    iosBundleId: 'com.example.esumbong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAua1SaD1Yi1As1tpGYfVgxOS6aOhwT8N0',
    appId: '1:776638379002:web:084b7e3e900f995143ea43',
    messagingSenderId: '776638379002',
    projectId: 'esumbong-1fd58',
    authDomain: 'esumbong-1fd58.firebaseapp.com',
    storageBucket: 'esumbong-1fd58.firebasestorage.app',
    measurementId: 'G-PYB6V4RXD6',
  );
}
